In [2]:
print("Hello world!")

Hello world!


In [1]:
import numpy
import pandas
import sklearn
import scipy
print("Hello world!")

Hello world!


In [3]:
print(1,2)

1 2


In [4]:
number = 42

In [5]:
print(number)

42


In [6]:
print(type(number))

<class 'int'>


In [7]:
print("Alte Ausgabe von %s %f" % ("Variablen", 3.141))

Alte Ausgabe von Variablen 3.141000


In [8]:
#Einzeiliger Kommentar
print("Kein Kommentar")

Kein Kommentar


In [9]:
"""
Das ist ein Blockkommentar
ueber mehrere Zeilen
"""

print("Das war ein Mehrzeiliger Kommentar")

Das war ein Mehrzeiliger Kommentar


In [10]:
example_list = ["test", "test2", "Katze", "test"]
print(example_list)
print(example_list[1])
print(example_list[-1])
print(example_list[-2])
print(example_list[2:3])
print(len(example_list))
example_list.remove("test")
print(example_list)

['test', 'test2', 'Katze', 'test']
test2
test
Katze
['Katze']
4
['test2', 'Katze', 'test']


In [11]:
my_tuple = ("one", "two", "three", "four")
print(my_tuple)

('one', 'two', 'three', 'four')


In [12]:
tr = {"Hello": "Hallo", "my": "mein", "friend": "Freund"}
print(tr["Hello"], tr["my"], tr["friend"])
print(tr.keys())
print(tr.values())

Hallo mein Freund
dict_keys(['Hello', 'my', 'friend'])
dict_values(['Hallo', 'mein', 'Freund'])


In [13]:
def func(param=1):
    result = param * 2
    if result > 10:
        return "Number too big!!!!"
    return result
    
print(func(2))
print(func())
print(func(6))

4
2
Number too big!!!!


In [14]:
number = 1
number += 1
print(number)

2


In [15]:
sentence = ['Hello', 'my', 'friend']
for word in sentence:
    print(tr[word], end=" ")

Hallo mein Freund 

In [16]:
for i in range(5):
    print(i)

0
1
2
3
4


In [17]:
squares = [i**2 for i in range(11)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [18]:
import numpy as np
print(np.zeros((5,5)))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [20]:
import matplotlib